
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: Password1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ruby_grad_test_development

test:
  <<: *default
  database: ruby_grad_test_test


#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: ruby_grad_test_production
  username: ruby_grad_test
  password: <%= ENV["RUBY_GRAD_TEST_DATABASE_PASSWORD"] %>
